const React = require("react");

const UserStories = ({ record }) => {
  const stories = record.params.stories;

  return React.createElement(
    "div",
    null,
    React.createElement(
      "h3",
      null,
      `Stories Generated by ${record.params.firstName} ${record.params.lastName}`
    ),
    React.createElement(
      "ul",
      null,
      stories.map((story, index) =>
        React.createElement(
          "li",
          { key: index },
          React.createElement("strong", null, story.title),
          ` - ${story.content.substring(0, 100)}...`
        )
      )
    )
  );
};

module.exports = UserStories;
